const domObjects = {
  img: document.querySelector("#img-id"),
  imageLoad: document.querySelector("#load-input"),
  brightness: document.querySelector("[id='0']"),
  blurFilter: document.querySelector("[id='1']"),
  contrast: document.querySelector("[id='2']"),
  pixelate: document.querySelector("[id='3']"),
  vibrance: document.querySelector("[id='4']"),
  opacity: document.querySelector("[id='5']"),
  saturate: document.querySelector("[id='6']"),
  noise: document.querySelector("[id='7']"),
  filterButton: document.querySelector(".filter-button"),
  rangeValueDisplay: document.querySelector(".range-value-display"),
  slider: document.querySelector(".slider"),
  resetBtnFilter: document.querySelector(".reset-filter-btn"),
  ratio: document.querySelector("#ratio"),
  makeCrop: document.querySelector("#make-crop"),
  transform: document.querySelector("#transform"),
  rotatePlus45: document.querySelector("#btn-rotate-plus90"),
  rotateMinus45: document.querySelector("#btn-rotate-minus90"),
  mirror: document.querySelector("#mirror"),
  flip: document.querySelector("#flip"),
  cropReset: document.querySelector("#crop-reset-btn"),
  canvas: document.querySelector(".canvas-style"),
  fineTuning: document.querySelector("#fine-tuning"),
  cropperDiv: document.querySelector(".image-div"),
};
export default domObjects;
